- name: AWX Diagnostic Test
  hosts: rocky.alyniar-chris.ddns.net
  gather_facts: false
  tasks:
    - name: Echo hostname
      ansible.builtin.command: hostname

    - name: Who am I
      ansible.builtin.command: whoami
