- name: Ensure Python 3.11 and pip are installed
  become: true
  ansible.builtin.package:
    name:
      - python3.11
      - python3.11-pip
    state: present

- name: Create target directory
  become: true
  ansible.builtin.file:
    path: /opt/vieve
    state: directory
    mode: '0755'

- name: Create static/uploads directory
  become: true
  ansible.builtin.file:
    path: /opt/vieve/static/uploads
    state: directory
    mode: '0755'

- name: Copy Flask app.py
  ansible.builtin.copy:
    src: app/app.py
    dest: /opt/vieve/app.py
    mode: '0755'

- name: Copy static assets
  ansible.builtin.copy:
    src: app/static/
    dest: /opt/vieve/static/
    mode: '0755'
    remote_src: no

- name: Copy HTML templates
  ansible.builtin.copy:
    src: app/templates/
    dest: /opt/vieve/templates/
    mode: '0755'
    remote_src: no

- name: Stop any running Flask app
  become: true
  ansible.builtin.shell: pkill -f app.py || true
  args:
    executable: /bin/bash
  ignore_errors: true

- name: Launch Flask app with Python 3.11
  become: true
  ansible.builtin.shell: nohup /usr/bin/python3.11 /opt/vieve/app.py > /opt/vieve/flask.log 2>&1 &
  args:
    executable: /bin/bash
