- name: Ensure Python 3.11 and pip are installed
  become: true
  ansible.builtin.package:
    name:
      - python3.11
      - python3.11-pip
    state: present

- name: Create target directory
  become: true
  ansible.builtin.file:
    path: /opt/vieve
    state: directory
    mode: '0755'

- name: Install Flask using Python 3.11
  become: true
  ansible.builtin.pip:
    name: flask
    executable: /usr/bin/python3.11
    extra_args:
      - -m
      - pip

- name: Copy Flask app.py
  ansible.builtin.copy:
    src: app.py
    dest: /opt/vieve/app.py
    mode: '0755'

- name: Copy static assets
  ansible.builtin.copy:
    src: static
    dest: /opt/vieve/static
    mode: '0755'
    remote_src: no

- name: Copy HTML templates
  ansible.builtin.copy:
    src: templates
    dest: /opt/vieve/templates
    mode: '0755'
    remote_src: no

- name: Launch Flask app with Python 3.11
  become: true
  ansible.builtin.shell: |
    nohup /usr/bin/python3.11 /opt/vieve/app.py > /opt/vieve/flask.log 2>&1 &
  args:
    executable: /bin/bash
