- name: Ensure Flask is installed
  ansible.builtin.pip:
    name: flask
    executable: pip3

- name: Create target directory
  ansible.builtin.file:
    path: /opt/vieve
    state: directory
    mode: '0755'

- name: Copy Flask app
  ansible.builtin.copy:
    src: app/app.py
    dest: /opt/vieve/app.py
    mode: '0755'

- name: Launch Flask app in background
  ansible.builtin.shell: |
    nohup python3 /opt/vieve/app.py > /opt/vieve/flask.log 2>&1 &
  args:
    executable: /bin/bash
